---
- name: Tomcat deployment playbook
  hosts: tomcat-nodes                           # Inventory hosts group / server to act on
  become: yes                                   # If to escalate privilege
  vars:
    tomcat_ver: 9.0.30                          # Tomcat version to install
    ui_manager_user: manager                    # User who can access the UI manager section only
    ui_manager_pass: VMware1!                   # UI manager user password
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: VMware1!                     # UI admin password
  roles:
    - tomcat

