---
- hosts: masters
  become: yes
  tasks:
    - name: Install Dcoker required packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2

    - name: Add Docker Repository
      yum_repository:
        name: Docker CE Stable - $basearch
        description: Docker CE Stable Repository
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: install Docker
      yum:
        name: docker-ce
        state: latest
        update_cache: true