- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['masters'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt